// FOR LOGIN
export const LOGIN_INITIATED = 'LOGIN_INITIATED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const CLEAR_LOGIN_STATE = 'CLEAR_LOGIN_STATE'

// CONSTANTS FOR REGISTRATION PROCESS OF AN ADMIN
export const REGISTRATION_INITIATED = 'REGISTRATION_INITIATED'
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS'
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED'
export const CLEAR_REGISTER_STATE = 'CLEAR_REGISTER_STATE'

// CONSTANTS FOR FETCHING PROCESS OF ADMINS
export const FETCH_ADMINS_INITIATED = 'FETCH_ADMINS_INITIATED'
export const FETCH_ADMINS_SUCCESS = 'FETCH_ADMINS_SUCCESS'

export const FETCH_ADMINS_INITIATED_NO_UPDATES_VERSION = 'FETCH_ADMINS_INITIATED_NO_UPDATES_VERSION'
export const FETCH_ADMINS_SUCCESS_NO_UPDATES_VERSION = 'FETCH_ADMINS_SUCCESS_NO_UPDATES_VERSION'

// CONSTANTS FOR DELETE PROCESS OF AN ADMIN
export const DELETE_ADMIN_INITIATED = 'DELETE_ADMIN_INITIATED'
export const DELETE_ADMIN_SUCCESS = 'DELETE_ADMIN_SUCCESS'

// CONSTANTS FOR FETCHING PROCESS OF AN ADMIN
export const FETCH_ADMIN_INITIATED = 'FETCH_ADMIN_INITIATED'
export const FETCH_ADMIN_SUCCESS = 'FETCH_ADMIN_SUCCESS'
export const FETCH_ADMIN_FAILED = 'FETCH_ADMIN_FAILED'

// CONSTANTS FOR UPDATING PROCESS OF AN ADMIN
export const UPDATE_ADMIN_INITIATED = 'UPDATE_ADMIN_INITIATED'
export const UPDATE_ADMIN_SUCCESS = 'UPDATE_ADMIN_SUCCESS'
export const UPDATE_ADMIN_FAILED = 'UPDATE_ADMIN_FAILED'

// CONSTANTS FOR FETCHING PROCESS OF A PROFILE
export const FETCH_PROFILE_INITIATED = 'FETCH_PROFILE_INITIATED'
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'
export const FETCH_PROFILE_FAILED = 'FETCH_PROFILE_FAILED'

// CONSTANTS FOR UPDATING PROCESS OF A PROFILE
export const UPDATE_PROFILE_INITIATED = 'UPDATE_PROFILE_INITIATED'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED'

// CONSTANTS FOR UPDATION OF A PROFILE PASSWORD
export const UPDATE_PASSWORD_INITIATED = 'UPDATE_PASSWORD_INITIATED'
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_FAILED = 'UPDATE_PASSWORD_FAILED'

// CONSTANTS FOR FETCHING TICKETS
export const FETCH_TICKETS_INITIATED = 'FETCH_TICKETS_INITIATED'
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS'
export const FETCH_TICKETS_FAILED = 'FETCH_TICKETS_FAILED'

export const SET_CURRENT_USER = 'SET_CURRENT_USER'

export const VALIDATIION_ERRORS = 'VALIDATIION_ERRORS'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'

// export const TASKS_FETCH_INITIATED = 'TASKS_FETCH_INITIATED'
// export const TASKS_FETCH_SUCCESS = 'TASKS_FETCH_SUCCESS'
export const POST_TASK_INITIATED = 'POST_TASK_INITIATED'
export const POST_TASK_SUCCESS = 'POST_TASK_SUCCESS'
export const POST_TASK_FAILED = 'POST_TASK_FAILED'
export const RESET_TASK_POST = 'RESET_TASK_POST'
export const CLEAR_FETCH_TASKS = 'CLEAR_FETCH_TASKS'

export const TASKS_FETCH_INITIATED = 'TASKS_FETCH_INITIATED'
export const TASK_FETCH_INITIATED_NO_UPDATES_VERSION = 'TASK_FETCH_INITIATED_NO_UPDATES_VERSION'
export const TASKS_FETCH_SUCCESS = 'TASKS_FETCH_SUCCESS'
export const TASK_FETCH_SUCCESS_NO_UPDATES_VERSION = 'TASK_FETCH_SUCCESS_NO_UPDATES_VERSION'

export const TASK_FETCH_INITIATED = 'TASK_FETCH_INITIATED'
export const TASK_FETCH_SUCCESS = 'TASK_FETCH_SUCCESS'
export const TASK_FETCH_FAILED = 'TASK_FETCH_FAILED'

export const ADD_COMMENT_INITIATED = 'ADD_COMMENT_INITIATED'
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'
export const ADD_COMMENT_FAILED = 'ADD_COMMENT_FAILED'

export const FETCH_OWN_PROFILE_INITIATED = 'FETCH_OWN_PROFILE_INITIATED'
export const FETCH_OWN_PROFILE_SUCCESS = 'FETCH_OWN_PROFILE_SUCCESS'
export const FETCH_OWN_PROFILE_FAILED = 'FETCH_OWN_PROFILE_FAILED'

export const UPDATE_OWN_PROFILE_INITIATED = 'UPDATE_OWN_PROFILE_INITIATED'
export const UPDATE_OWN_PROFILE_SUCCESS = 'UPDATE_OWN_PROFILE_SUCCESS'
export const UPDATE_OWN_PROFILE_FAILED = 'UPDATE_OWN_PROFILE_FAILED'

export const TASKS_FETCH_INITIATED_NO_UPDATES_VERSION = 'TASKS_FETCH_INITIATED_NO_UPDATES_VERSION'

export const TASKS_FETCH_SUCCESS_NO_UPDATES_VERSION = 'TASKS_FETCH_SUCCESS_NO_UPDATES_VERSION'

export const CONVERSATIONS_FETCH_INITIATED = 'CONVERSATIONS_FETCH_INITIATED'
export const CONVERSATIONS_FETCH_SUCCESS = 'CONVERSATIONS_FETCH_SUCCESS'

export const MESSAGES_FETCH_INITIATED = 'MESSAGES_FETCH_INITIATED'
export const MESSAGES_FETCH_SUCCESS = 'MESSAGES_FETCH_SUCCESS'

export const SET_IO = 'SET_IO'

export const SET_CURRENT_CHAT_USER_ID = 'SET_CURRENT_CHAT_USER_ID'

export const SEND_MESSAGE_INITIATED = 'SEND_MESSAGE_INITIATED'
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'

export const UPDATE_LOCAL_CHAT = 'UPDATE_LOCAL_CHAT'

export const RESET_TASK_UPDATE = 'RESET_TASK_UPDATE'

export const UPDATE_TASK_INITIATED = 'UPDATE_TASK_INITIATED'
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS'
export const UPDATE_TASK_FAILED = 'UPDATE_TASK_FAILED'

export const DELETE_TASK_INITIATED = 'DELETE_TASK_INITIATED'
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS'
export const DELETE_TASK_FAILED = 'DELETE_TASK_FAILED'

export const POST_OFFER_INITIATED = 'POST_OFFER_INITIATED'
export const POST_OFFER_SUCCESS = 'POST_OFFER_SUCCESS'
export const POST_OFFER_FAILED = 'POST_OFFER_FAILED'
export const RESET_OFFER_POST = 'RESET_OFFER_POST'

export const FETCH_ORDER_INITIATED = 'FETCH_ORDER_INITIATED'
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS'
export const FETCH_ORDER_FAILED = 'FETCH_ORDER_FAILED'

export const HIRE_WORKER_INITIATED = 'HIRE_WORKER_INITIATED'
export const HIRE_WORKER_SUCCESS = 'HIRE_WORKER_SUCCESS'
export const HIRE_WORKER_FAILED = 'HIRE_WORKER_FAILED'
export const RESET_HIRE_WORKER = 'RESET_HIRE_WORKER'

export const CLEAR_CHAT_DATA = 'CLEAR_CHAT_DATA'

export const HANDLE_MARK_ORDER_COMPLETE_INITIATED = 'HANDLE_MARK_ORDER_COMPLETE_INITIATED'

export const HANDLE_MARK_ORDER_COMPLETE_SUCCESS = 'HANDLE_MARK_ORDER_COMPLETE_SUCCESS'

export const HANDLE_MARK_ORDER_COMPLETE_FAILED = 'HANDLE_MARK_ORDER_COMPLETE_FAILED'

export const RESET_ORDER_COMPLETE = 'RESET_ORDER_COMPLETE'
